global:
  scrape_interval: 15s # How frequently Prometheus will scrape targets
  evaluation_interval: 15s # How frequently Prometheus will evaluate rules

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['localhost:5000'] # Your Flask app's host and port
        labels:
          application: 'DelinquencyPredictor'